In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [2]:
train=pd.read_csv(r"C:\Users\shash\Downloads\archive (2)\train (1).csv")
test=pd.read_csv(r"C:\Users\shash\Downloads\archive (2)\test (1).csv")
print(train.shape)
print(test.shape)

(1460, 81)
(1459, 80)


In [36]:
xtrain=train.drop(columns="SalePrice")
ytrain=train["SalePrice"]
xtest=test.copy()

Missing Value Imputation

In [37]:
numvar=xtrain.select_dtypes(include=[int,float]).columns
isnullsum=xtrain.isnull().sum()
numvarmiss=[var for var in numvar if isnullsum[var]>0]

In [30]:
numvarmiss
numvarmean=['LotFrontage', 'MasVnrArea']
numvarmedian=['GarageYrBlt']

In [23]:
catvar=xtrain.select_dtypes(include=[object]).columns
isnullsum=xtrain.isnull().sum()
catvarmiss=[var for var in catvar if isnullsum[var]>0]

In [24]:
catvarmiss

['Alley',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [49]:
catvarmode=['Alley',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2','Electrical',
 'FireplaceQu']
catvarconst=[
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [50]:
meanimputer=Pipeline(steps=[("imputer",SimpleImputer(strategy="mean"))])
medianimputer=Pipeline(steps=[("imputer",SimpleImputer(strategy="median"))])
modeimputer=Pipeline(steps=[("imputer",SimpleImputer(strategy="most_frequent"))])
constimputer=Pipeline(steps=[("imputer",SimpleImputer(strategy="constant",fill_value="MissingValue"))])       

In [54]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num_mean", meanimputer, numvarmean),
        ("num_median", medianimputer, numvarmedian),
        ("cat_mode", modeimputer, catvarmode),
        ("cat_const", constimputer, catvarconst)
    ]
)

In [55]:
preprocessor.fit(xtrain)

ColumnTransformer(transformers=[('num_mean',
                                 Pipeline(steps=[('imputer', SimpleImputer())]),
                                 ['LotFrontage', 'MasVnrArea']),
                                ('num_median',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['GarageYrBlt']),
                                ('cat_mode',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent'))]),
                                 ['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond',
                                  'BsmtExposure', 'BsmtFinType1',
                                  'BsmtFinType2', 'Electrical',
                                  'FireplaceQu']),
                                ('cat_const',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(fill_value='MissingValue',
                                                                strategy='constant'))]),
                                 ['GarageType', 'GarageFinish', 'GarageQual',
                                  'GarageCond', 'PoolQC', 'Fence',
                                  'MiscFeature'])])

In [60]:
X_train_processed = preprocessor.transform(xtrain)
X_train_processed

array([[65.0, 196.0, 2003.0, ..., 'MissingValue', 'MissingValue',
        'MissingValue'],
       [80.0, 0.0, 1976.0, ..., 'MissingValue', 'MissingValue',
        'MissingValue'],
       [68.0, 162.0, 2001.0, ..., 'MissingValue', 'MissingValue',
        'MissingValue'],
       ...,
       [66.0, 0.0, 1941.0, ..., 'MissingValue', 'GdPrv', 'Shed'],
       [68.0, 0.0, 1950.0, ..., 'MissingValue', 'MissingValue',
        'MissingValue'],
       [75.0, 0.0, 1965.0, ..., 'MissingValue', 'MissingValue',
        'MissingValue']], shape=(1460, 19), dtype=object)

In [66]:
preprocessor.named_transformers_["num_mean"].named_steps["imputer"].statistics_

array([ 70.04995837, 103.68526171])

In [67]:
train["LotFrontage"].mean()

np.float64(70.04995836802665)

In [68]:
xtrainclean=preprocessor.transform(xtrain)
xtestclean=preprocessor.transform(xtest)

In [69]:
xtrainclean

array([[65.0, 196.0, 2003.0, ..., 'MissingValue', 'MissingValue',
        'MissingValue'],
       [80.0, 0.0, 1976.0, ..., 'MissingValue', 'MissingValue',
        'MissingValue'],
       [68.0, 162.0, 2001.0, ..., 'MissingValue', 'MissingValue',
        'MissingValue'],
       ...,
       [66.0, 0.0, 1941.0, ..., 'MissingValue', 'GdPrv', 'Shed'],
       [68.0, 0.0, 1950.0, ..., 'MissingValue', 'MissingValue',
        'MissingValue'],
       [75.0, 0.0, 1965.0, ..., 'MissingValue', 'MissingValue',
        'MissingValue']], shape=(1460, 19), dtype=object)

In [71]:
preprocessor.transformers_

[('num_mean',
  Pipeline(steps=[('imputer', SimpleImputer())]),
  ['LotFrontage', 'MasVnrArea']),
 ('num_median',
  Pipeline(steps=[('imputer', SimpleImputer(strategy='median'))]),
  ['GarageYrBlt']),
 ('cat_mode',
  Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent'))]),
  ['Alley',
   'MasVnrType',
   'BsmtQual',
   'BsmtCond',
   'BsmtExposure',
   'BsmtFinType1',
   'BsmtFinType2',
   'Electrical',
   'FireplaceQu']),
 ('cat_const',
  Pipeline(steps=[('imputer',
                   SimpleImputer(fill_value='MissingValue',
                                 strategy='constant'))]),
  ['GarageType',
   'GarageFinish',
   'GarageQual',
   'GarageCond',
   'PoolQC',
   'Fence',
   'MiscFeature']),
 ('remainder',
  'drop',
  ['Id',
   'MSSubClass',
   'MSZoning',
   'LotArea',
   'Street',
   'LotShape',
   'LandContour',
   'Utilities',
   'LotConfig',
   'LandSlope',
   'Neighborhood',
   'Condition1',
   'Condition2',
   'BldgType',
   'HouseStyle',
   'OverallQual',
   

In [72]:
pd.DataFrame(xtrainclean,columns=numvarmean+numvarmedian+catvarmode+catvarconst)

LotFrontage MasVnrArea GarageYrBlt Alley MasVnrType BsmtQual BsmtCond  \
0           65.0      196.0      2003.0  Grvl    BrkFace       Gd       TA   
1           80.0        0.0      1976.0  Grvl    BrkFace       Gd       TA   
2           68.0      162.0      2001.0  Grvl    BrkFace       Gd       TA   
3           60.0        0.0      1998.0  Grvl    BrkFace       TA       Gd   
4           84.0      350.0      2000.0  Grvl    BrkFace       Gd       TA   
...          ...        ...         ...   ...        ...      ...      ...   
1455        62.0        0.0      1999.0  Grvl    BrkFace       Gd       TA   
1456        85.0      119.0      1978.0  Grvl      Stone       Gd       TA   
1457        66.0        0.0      1941.0  Grvl    BrkFace       TA       Gd   
1458        68.0        0.0      1950.0  Grvl    BrkFace       TA       TA   
1459        75.0        0.0      1965.0  Grvl    BrkFace       TA       TA   

     BsmtExposure BsmtFinType1 BsmtFinType2 Electrical FireplaceQu GarageType  \
0              No          GLQ          Unf      SBrkr          Gd     Attchd   
1              Gd          ALQ          Unf      SBrkr          TA     Attchd   
2              Mn          GLQ          Unf      SBrkr          TA     Attchd   
3              No          ALQ          Unf      SBrkr          Gd     Detchd   
4              Av          GLQ          Unf      SBrkr          TA     Attchd   
...           ...          ...          ...        ...         ...        ...   
1455           No          Unf          Unf      SBrkr          TA     Attchd   
1456           No          ALQ          Rec      SBrkr          TA     Attchd   
1457           No          GLQ          Unf      SBrkr          Gd     Attchd   
1458           Mn          GLQ          Rec      FuseA          Gd     Attchd   
1459           No          BLQ          LwQ      SBrkr          Gd     Attchd   

     GarageFinish GarageQual GarageCond        PoolQC         Fence  \
0             RFn         TA         TA  MissingValue  MissingValue   
1             RFn         TA         TA  MissingValue  MissingValue   
2             RFn         TA         TA  MissingValue  MissingValue   
3             Unf         TA         TA  MissingValue  MissingValue   
4             RFn         TA         TA  MissingValue  MissingValue   
...           ...        ...        ...           ...           ...   
1455          RFn         TA         TA  MissingValue  MissingValue   
1456          Unf         TA         TA  MissingValue         MnPrv   
1457          RFn         TA         TA  MissingValue         GdPrv   
1458          Unf         TA         TA  MissingValue  MissingValue   
1459          Fin         TA         TA  MissingValue  MissingValue   

       MiscFeature  
0     MissingValue  
1     MissingValue  
2     MissingValue  
3     MissingValue  
4     MissingValue  
...            ...  
1455  MissingValue  
1456  MissingValue  
1457          Shed  
1458  MissingValue  
1459  MissingValue  

[1460 rows x 19 columns]